import { defineSkill } from "../define";

/**
 * Hooks configuration teaching skill (Z1, the zero-mechanism deferred item):
 * a reference for writing hook declarations in THIS harness - the merged
 * top-level "hooks:" key, the five events, matcher semantics, the runner's
 * constraints, and the veto/injection effects. Adapted from the reference
 * project's configuration reference; event names, limits and effects follow
 * this repo's plugin-hooks implementation.
 */
export const hooksConfigurationSkill = defineSkill(
  "hooks-configuration",
  "Write and debug hook declarations for this harness: where the merged hooks key lives, the five lifecycle events, matcher semantics, runner constraints (no shell, bounded timeouts), and what veto or context-injection a hook's exit and output produce",
  [
    "# Hooks configuration",
    "",
    "Hooks run commands at fixed points of a session's lifecycle. They are",
    "declarative: no code registers them at runtime - you write them into",
    "configuration, the session picks them up when it is built.",
    "",
    "## Where declarations live",
    "",
    'One top-level "hooks:" key, merged from two layers:',
    "",
    "- project layer: <workspaceRoot>/plugins.yml (or .innocence/plugins.yml)",
    "- user layer: ~/.innocence/cordis.yml",
    "",
    "Project declarations override user declarations for the same key (atomic",
    "key override, not a list merge). An empty or missing key mounts no hooks -",
    "the session runs exactly as before.",
    "",
    "## Declaration shape",
    "",
    "    hooks:",
    "      preToolCall:",
    "        - match: Write",
    "          command: node .innocence/hooks/check-write.js",
    "          timeoutMs: 10000",
    "",
    "Each entry has three fields: command (required - the executable plus its",
    "arguments), match (optional), and timeoutMs (optional). Unknown fields",
    "and invalid entries are skipped with a warning, never fail the session.",
    "",
    "- match on a TOOL event is an exact tool-name equality (Write, Edit, Read,",
    "  Bash, Glob, Grep...); on an INPUT event (userPromptSubmit) it is an input",
    "  prefix test. No matcher = the hook fires for every occurrence of the event.",
    "- timeoutMs defaults to 10 seconds and is capped at 30; a timed-out hook",
    "  counts as failed, never blocks.",
    "",
    "## The five events",
    "",
    "| Event | Fires | Matcher meaning |",
    "|---|---|---|",
    "| sessionStart | once, when the first session in the process starts | - |",
    "| userPromptSubmit | for every user message | input prefix |",
    "| preToolCall | before each tool call; can veto | tool name |",
    "| postToolCall | after a successful tool call | tool name |",
    "| sessionStop | when a session unwinds (skipped on host shutdown) | - |",
    "",
    "## What the runner gives you",
    "",
    "- The command runs WITHOUT a shell (execFile semantics): the first token is",
    "  the executable, the rest are literal arguments - no pipes, redirection or",
    "  quoting tricks. Write a small script file when you need logic.",
    "- The working directory is the session's workspace root.",
    "- stdout is clamped to 8 KB; longer output is truncated.",
    "- Every command passes a first-encounter permission gate (action \"run\",",
    "  scope = the executable) before it may run; an allowed command is",
    "  remembered for the session, a denied one is re-asked.",
    "",
    "## Effects: veto and context injection",
    "",
    "- A tool event hook VETOES the call only by exiting non-zero. The veto text",
    "  (stdout) reaches the model as a continuation note on its next turn, and",
    "  the call is refused. Exit zero = no opinion.",
    "- A postToolCall hook's stdout is appended to the tool result as a note.",
    "- Infrastructure failures (spawn errors, timeouts) never block anything:",
    "  they surface as deferred warnings.",
    "- sessionStop is fail-soft and bounded; it never delays teardown beyond its",
    "  grace window.",
    "",
    "## Patterns that work here",
    "",
    "Log every command the session runs (pre-tool, exact name match):",
    "",
    "    hooks:",
    "      preToolCall:",
    "        - match: Bash",
    "          command: node .innocence/hooks/log-command.js",
    "",
    "Reformat files after successful writes (post-tool note on the result):",
    "",
    "    hooks:",
    "      postToolCall:",
    "        - match: Write",
    "          command: node .innocence/hooks/format-written.js",
    "",
    "Debug order when a hook does not fire: check the layer merge (was the key",
    "overridden?), the matcher kind (exact tool name, not a pattern), the",
    "first-encounter permission (was it denied?), and the no-shell rule (a",
    "command that assumes a shell fails to spawn and only warns).",
  ].join("\n"),
);
